//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.7
//
// <auto-generated>
//
// Generated from file `Hello.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

/* eslint-disable */
/* jshint ignore: start */

import '/node_modules/ice/lib/Ice.js'
//import { Ice } from "ice";

const _ModuleRegistry = Ice._ModuleRegistry;
const Slice = Ice.Slice;

let Demo = _ModuleRegistry.module("Demo");

const iceC_Demo_Hello_ids = [
    "::Demo::Hello",
    "::Ice::Object"
];

Demo.Hello = class extends Ice.Object
{
};

Demo.HelloPrx = class extends Ice.ObjectPrx
{
};

Slice.defineOperations(Demo.Hello, Demo.HelloPrx, iceC_Demo_Hello_ids, 0,
{
    "sayHello": [, 2, 2, , , [[3]], , , , ]
});
export { Demo };
